#!/bin/bash
email=jyang10@tulane.edu
data=/lustre/project/wdeng7/jyang10/data/round2
transcriptome=/lustre/project/wdeng7/deep/CellRangerData/refgenome4cellranger
ID=B7_round2
sample_name=B7_1,B7_2,B7_3,B7_4
maskfile1=/lustre/project/wdeng7/deep/dm6/dm6_rmsk.gtf
maskfile2=/lustre/project/wdeng7/deep/dm6/genes/Drosophila_melanogaster.BDGP6.28.100.chr_filtered.GAL4.EGFP.gtf
outputloom=/lustre/project/wdeng7/jyang10/data/round2/result
